trigger:
- main
pool:
  vmImage: ubuntu-latest

parameters:
  - name: initialValue
    type: string
    default: A value
    displayName: initial vlaue

stages:
  - stage: Stage1
    displayName: Stage 1
    jobs:
    - job: Job1
      displayName: Job 1.1
      steps:
      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            myValue=`echo ${{ parameters.initialValue }}`
            echo "my value is $myValue"
            echo "##vso[task.setvariable variable=anotherValue;isoutput=true]$myValue"
        displayName: Bash script 1
        name: Script1
  - stage: Stage2
    displayName: Stage 2
    jobs:
    - job: Job2
      variables:
        myStageAVar: $[ stageDependencies.Stage1.Job1.outputs['Script1.anotherValue'] ]
      displayName: Job 2.2
      steps:
      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            echo "my value is $(myStageVar)"
          displayName: Bash script 2
