trigger:
- main
pool:
  vmImage: ubuntu-latest


parameters:
  -name: initialValue
   type: string
   default: A value

stages:
  - stage: Stage1
    displayName: Stage 1
    jobs:
    - job: Job1
      displayName: Job 1
      steps:
      - script: |
          echo hello world $(initialValue)
        displayName: A bash script