trigger:
- main
pool:
  vmImage: ubuntu-latest

parameters:
  - name: initialValue
    type: string
    default: A value
    displayName: initial vlaue

stages:
  - stage: Stage1
    displayName: Stage 1
    jobs:
    - job: Job1
      displayName: Job 1
      steps:
      - task: Bash@3
        inputs:
          targetType: "inline"
          script: env
        displayName: A bash script