trigger:
- main
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Stage1
    displayName: Stage 1
    jobs:
    - job: Job1
      displayName: Job 1
      steps:
      - script: |
          echo hello world
        displayName: A bash script